name: HTML Validator

on:
  push:
    branches:
    - master
    - gh-pages
  pull_request:
    branches:
    - master
    - gh-pages

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: ./action-html-validation



